version: '3.8'

services:
  web:
    build:
      context: .
      args:
        # This passes the API_KEY from your .env file into the build process
        API_KEY: ${API_KEY}
    ports:
      - "8080:80"
    restart: unless-stopped
    container_name: ai-hairstyle-app
